#!/usr/bin/env python3

""" Used to communicate with the Arduino powered control panel """

import serial
import time
import uinput

bmap =  {
            64 : uinput.BTN_JOYSTICK
        }

def setup(tty, baud):
    """ Setup the connection with the Arduino """
    connect = lambda args: serial.Serial(args[0], args[1])
    connected = False
    tries = 0
    while not connected and tries < 3:
        try:
            ser = connect((tty, baud))
            connected = True
        except serial.SerialException as _:
            tries += 1
    if not connected:
        print("Unable to connect")
        return


    ser.setDTR(False)
    ser.flushInput()
    ser.setDTR(True)

    ready = False
    while not ready:
        data = ser.readline().decode("ascii")
        print("|"+data+"|")
        if data[0] == "R":
            print("Ready")
            ready = True
    ser.write(b'\x01')

    main(ser)
    close(ser)

def main(ser):
    """ Execute the main logic of the program """
    events = (
             uinput.BTN_JOYSTICK,
             uinput.ABS_X + (0, 1024, 0, 0),
             uinput.ABS_Y + (0, 1024, 0, 0),
             uinput.ABS_Z + (0, 1024, 0, 0)""",
             uinput.BTN_A,
             uinput.BTN_B"""
    )
    device = uinput.Device(events)
    x = int(1024/2)
    y = int(1024/2)
    z = int(1024/2)
    button = {}
    run = True
    while run:
        try:
            data = ser.readline().decode("ascii")
            action = ord(data[0])
            pin = ord(data[1])
            value = int(data[2:])
            if action == 97: #Analog Input
                if pin == 'x':
                    device.emit(uinput.ABS_X, abs(value - 1024), syn=False)
                elif pin == 'y':
                    device.emit(uinput.ABS_Y, value)
                elif pin == 'z':
                    device.emit(uinput.ABS_Z, value)
            elif action == 98: #Button
                if value != button[pin]:
                    device.emit(bmap[pin], value)
                    button[pin] = value
                    print("Button Press:",pin)

        except KeyboardInterrupt as _:
            run = False
        except Exception as e:
            run = False
            print(e)

def close(ser):
    """ Close the connection with the arduino """
    print("Closing")
    ser.write(b'\x00')
    ser.close()

if __name__ == "__main__":
    setup("/dev/ttyACM0", 57600)
