#!/usr/bin/env python3

""" Used to communicate with the Arduino power control panel """

import serial
import uinput

def setup(tty, baud):
    """ Setup the connection with the Arduino """
    connect = lambda args: serial.Serial(args[0], args[1])
    connected = False
    tries = 0
    while not connected and tries < 3:
        try:
            ser = connect((tty, baud))
            connected = True
        except serial.SerialException as _:
            tries += 1
    if not connected:
        print("Unable to connect")
        return


    ser.setDTR(False)
    ser.flushInput()
    ser.setDTR(True)

    main(ser)
    close(ser)

def main(ser):
    """ Execute the main logic of the program """
    events = (uinput.BTN_JOYSTICK, uinput.ABS_X + (0, 1024, 0, 0),uinput.ABS_Y + (0, 1024, 0, 0))
    device = uinput.Device(events)
    x = int(1024/2)
    y = int(1024/2)
    while True:
        try:
            data = ser.readline().decode("UTF-8")
            axis = str(data[0])
            value = int(data[1:])
            if axis == 'x':
                device.emit(uinput.ABS_X, abs(value - 1024), syn=False)
            else:
                device.emit(uinput.ABS_Y, value)
        except Exception as e:
            print(e)

def close(ser):
    """ Close the connection with the arduino """
    ser.close()

if __name__ == "__main__":
    setup("/dev/ttyACM0", 57600)
